/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-14 11:19:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.write;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.List;
import poly.util.CmmUtil;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/view/inc/preloader.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/jsfile.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("jar:file:/D:/SpringProject/SeeSpeech/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringPRJ/WEB-INF/lib/spring-webmvc-4.3.27.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1588032890000L));
    _jspx_dependants.put("/WEB-INF/view/inc/header.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/footer.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/head.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/section.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.27.RELEASE.jar", Long.valueOf(1635409831198L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- head Start -->\r\n");
      out.write("    ");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>S&S</title>\n");
      out.write("<meta name=\"description\" content=\"See&Speech\">\n");
      out.write("<meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/hero/hero2.png\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\">\n");
      out.write("\n");
      out.write("<!-- CSS here -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slicknav.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themify-icons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slick.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fontawesome-free-5.15.3-web/css/all.min.css\">");
      out.write("\r\n");
      out.write("    <!-- head end -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/page/quizPlay.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        b {\r\n");
      out.write("            color: red;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Preloader Start -->\r\n");
      out.write("\n");
      out.write("<div id=\"preloader-active\">\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"preloader-inner position-relative\">\n");
      out.write("            <div class=\"preloader-circle\"></div>\n");
      out.write("            <div class=\"preloader-img pere-text\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snsloder.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- Preloader end -->\r\n");
      out.write("\r\n");
      out.write("<!-- right loader start-->\r\n");
      out.write("<div id=\"right-loader-active\" style=\"display: none\">\r\n");
      out.write("    <div class=\"right_loader d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"preloader-inner position-relative\">\r\n");
      out.write("            <div class=\"right_loader_icon pere-text\">\r\n");
      out.write("                <i class=\"far fa-check-circle fa-3x\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- right loader end-->\r\n");
      out.write("\r\n");
      out.write("<!-- header start -->\r\n");
      out.write('\n');
      out.write('\n');

    String SS_USER_EMAIL = CmmUtil.nvl((String) session.getAttribute("SS_USER_EMAIL"));

      out.write("\n");
      out.write("<header>\n");
      out.write("    <div class=\"header-area header-transparent\">\n");
      out.write("        <div class=\"main-header \">\n");
      out.write("            <div class=\"header-bottom  header-sticky\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"row align-items-center\">\n");
      out.write("                        <!-- Logo -->\n");
      out.write("                        <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                            <div class=\"logo\">\n");
      out.write("                                <a href=\"index.do\"><img\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snslogo.png\" alt=\"\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                            <div class=\"menu-wrapper d-flex align-items-center justify-content-end\">\n");
      out.write("                                <!-- Main-menu -->\n");
      out.write("                                <div class=\"main-menu d-none d-lg-block\">\n");
      out.write("                                    <nav>\n");
      out.write("                                        <ul id=\"navigation\">\n");
      out.write("                                            <li class=\"active\"><a href=\"index.do\">Home</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"userPage.do\">User</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"rank.do\">Rank</a></li>\n");
      out.write("                                            <!-- Button -->\n");
      out.write("                                            ");
 if (SS_USER_EMAIL.equals("")) { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"loginPage.do\" class=\"btn btn3\">Log in</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } else { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"logout.do\" class=\"btn btn3\">Log out</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } 
      out.write("\n");
      out.write("                                        </ul>\n");
      out.write("                                    </nav>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Mobile Menu -->\n");
      out.write("                        <div class=\"col-12\">\n");
      out.write("                            <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("<!-- header end -->\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("    <!-- slider Area Start-->\r\n");
      out.write("    ");
      out.write("\n");
      out.write("<section class=\"slider-area slider-area2\">\n");
      out.write("    <div class=\"slider-active\">\n");
      out.write("        <!-- Single Slider -->\n");
      out.write("        <div class=\"single-slider slider-height2\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-xl-8 col-lg-11 col-md-12\">\n");
      out.write("                        <div class=\"hero__caption hero__caption2\">\n");
      out.write("                            <h1 data-animation=\"bounceIn\" data-delay=\"0.2s\">See & Speech</h1>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("    <!-- slider Area end-->\r\n");
      out.write("\r\n");
      out.write("    <!-- 다이어리쓰기-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"comment-form\" style=\"margin:20px 200px 20px 200px\">\r\n");
      out.write("        <div class=\"col-12\">\r\n");
      out.write("            <h1 class=\"contact-title\">오늘의 일기쓰기</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form class=\"form-contact comment_form\" action=\"#\" id=\"commentForm\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input class=\"form-control\" name=\"website\" id=\"website\" type=\"text\" placeholder=\"Title\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <textarea class=\"form-control w-100\" name=\"comment\" id=\"comment\" cols=\"30\" rows=\"9\" placeholder=\"Write Comment\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"micButtonBox\" class=\"row justify-content-sm-center mic_box\" style=\"margin-top: 30px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row justify-content-sm-center\" style=\"margin-bottom: 20px\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 col-sm-8 button_container\">\r\n");
      out.write("                    <button type=\"submit\" class=\"boxed-btn play_button next_button\" >Submit</button>\r\n");
      out.write("                    <button class=\"boxed-btn play_button\" onclick=\"doList()\">List</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function doList() {\r\n");
      out.write("        window.open('http://localhost:8989/writelist.do');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<!-- footer&Scroll Up start -->\r\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-wrappper footer-bg\">\n");
      out.write("        <!-- footer-bottom area -->\n");
      out.write("        <div class=\"footer-bottom-area\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"footer-border\">\n");
      out.write("                    <div class=\"row d-flex align-items-center\">\n");
      out.write("                        <div class=\"col-xl-12 \">\n");
      out.write("                            <div class=\"footer-copy-right text-center\">\n");
      out.write("                                <p>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>\n");
      out.write("                                    All rights reserved | This template is made with <i class=\"fa fa-heart\"\n");
      out.write("                                                                                        aria-hidden=\"true\"></i> by <a\n");
      out.write("                                        href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Scroll Up -->\n");
      out.write("<div id=\"back-top\">\n");
      out.write("    <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- footer&Scroll Up end -->\r\n");
      out.write("\r\n");
      out.write("<!-- js file start -->\r\n");
      out.write("\n");
      out.write("<!-- JS here -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modernizr-3.5.0.min.js\"></script>\n");
      out.write("<!-- Jquery, Popper, Bootstrap -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\n");
      out.write("<!-- Jquery Mobile Menu -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.slicknav.min.js\"></script>\n");
      out.write("<!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/slick.min.js\"></script>\n");
      out.write("<!-- Progress -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.barfiller.js\"></script>\n");
      out.write("<!-- counter , waypoint,Hover Direction -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/hover-direction-snake.min.js\"></script>\n");
      out.write("<!-- Jquery Plugins, main Jquery -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>");
      out.write("\r\n");
      out.write("<!-- js file end -->\r\n");
      out.write("\r\n");
      out.write("<!-- annyang js & speechkitt -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/annyang.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/speechkitt.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    if (annyang) {\r\n");
      out.write("        // Add our commands to annyang\r\n");
      out.write("        annyang.addCommands({});\r\n");
      out.write("\r\n");
      out.write("        //음성인식 값 받아오기위한 객체 생성\r\n");
      out.write("        let recognition = annyang.getSpeechRecognizer();\r\n");
      out.write("        //최종 음성인식 결과값 저장 변수\r\n");
      out.write("        let final_transcript = \"\";\r\n");
      out.write("        //말하는 동안에 인식되는 값 가져오기(허용)\r\n");
      out.write("        recognition.interimResults = true;\r\n");
      out.write("        //음성 인식결과 가져오기\r\n");
      out.write("        recognition.onresult = function (event) {\r\n");
      out.write("            final_transcript = \"\";\r\n");
      out.write("            for (let i = event.resultIndex; i < event.results.length; ++i) {\r\n");
      out.write("                if (event.results[i].isFinal) {\r\n");
      out.write("                    final_transcript += event.results[i][0].transcript;\r\n");
      out.write("                    final_transcript = final_transcript.trim();\r\n");
      out.write("                    console.log(\"final :\" + final_transcript);\r\n");
      out.write("                }else{\r\n");
      out.write("                    interim_transcript+= event.results[i][0].transcript;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            document.getElementById(\"comment\").innerHTML+=final_transcript;\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Tell KITT to use annyang\r\n");
      out.write("        SpeechKITT.annyang();\r\n");
      out.write("\r\n");
      out.write("        // Define a stylesheet for KITT to use\r\n");
      out.write("        SpeechKITT.setStylesheet('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themes/flat.css');\r\n");
      out.write("\r\n");
      out.write("        // Render KITT's interface\r\n");
      out.write("        SpeechKITT.vroom();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
