/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-14 11:18:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import poly.util.CmmUtil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/view/inc/preloader.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/jsfile.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/indexSingle.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/header.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/footer.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/head.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/section.jsp", Long.valueOf(1634277451000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    String SS_USER_TYPE = CmmUtil.nvl((String) session.getAttribute("SS_USER_TYPE"));

    List<Map<String, String>> rQuizList = (List<Map<String, String>>) request.getAttribute("rQuizList");
    List<String> rUserQuizTitleList = (List<String>) request.getAttribute("rUserQuizTitleList");

    if (rQuizList == null) {
        rQuizList = new ArrayList<>();
    }

    if (rUserQuizTitleList == null) {
        rUserQuizTitleList = new ArrayList<>();
    }


      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!-- head Start -->\n");
      out.write("    ");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>S&S</title>\n");
      out.write("<meta name=\"description\" content=\"See&Speech\">\n");
      out.write("<meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/hero/hero2.png\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\">\n");
      out.write("\n");
      out.write("<!-- CSS here -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slicknav.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themify-icons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slick.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fontawesome-free-5.15.3-web/css/all.min.css\">");
      out.write("\n");
      out.write("    <!-- head end -->\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/page/index.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- Preloader Start -->\n");
      out.write("\n");
      out.write("<div id=\"preloader-active\">\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"preloader-inner position-relative\">\n");
      out.write("            <div class=\"preloader-circle\"></div>\n");
      out.write("            <div class=\"preloader-img pere-text\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snsloder.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("<!-- Preloader end -->\n");
      out.write("\n");
      out.write("<!-- header start -->\n");
      out.write('\n');
      out.write('\n');

    String SS_USER_EMAIL = CmmUtil.nvl((String) session.getAttribute("SS_USER_EMAIL"));

      out.write("\n");
      out.write("<header>\n");
      out.write("    <div class=\"header-area header-transparent\">\n");
      out.write("        <div class=\"main-header \">\n");
      out.write("            <div class=\"header-bottom  header-sticky\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"row align-items-center\">\n");
      out.write("                        <!-- Logo -->\n");
      out.write("                        <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                            <div class=\"logo\">\n");
      out.write("                                <a href=\"index.do\"><img\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snslogo.png\" alt=\"\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                            <div class=\"menu-wrapper d-flex align-items-center justify-content-end\">\n");
      out.write("                                <!-- Main-menu -->\n");
      out.write("                                <div class=\"main-menu d-none d-lg-block\">\n");
      out.write("                                    <nav>\n");
      out.write("                                        <ul id=\"navigation\">\n");
      out.write("                                            <li class=\"active\"><a href=\"index.do\">Home</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"userPage.do\">User</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"rank.do\">Rank</a></li>\n");
      out.write("                                            <!-- Button -->\n");
      out.write("                                            ");
 if (SS_USER_EMAIL.equals("")) { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"loginPage.do\" class=\"btn btn3\">Log in</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } else { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"logout.do\" class=\"btn btn3\">Log out</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } 
      out.write("\n");
      out.write("                                        </ul>\n");
      out.write("                                    </nav>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Mobile Menu -->\n");
      out.write("                        <div class=\"col-12\">\n");
      out.write("                            <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("<!-- header end -->\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("    <!-- slider Area Start-->\n");
      out.write("    ");
      out.write("\n");
      out.write("<section class=\"slider-area slider-area2\">\n");
      out.write("    <div class=\"slider-active\">\n");
      out.write("        <!-- Single Slider -->\n");
      out.write("        <div class=\"single-slider slider-height2\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-xl-8 col-lg-11 col-md-12\">\n");
      out.write("                        <div class=\"hero__caption hero__caption2\">\n");
      out.write("                            <h1 data-animation=\"bounceIn\" data-delay=\"0.2s\">See & Speech</h1>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>");
      out.write("\n");
      out.write("    <!-- slider Area end-->\n");
      out.write("\n");
      out.write("    <!-- 단어 학습하기 start -->\n");
      out.write("    <!-- Courses area start -->\n");
      out.write("    <div class=\"courses-area section-padding40 fix\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <div class=\"col-xl-7 col-lg-8\">\n");
      out.write("                    <div class=\"section-tittle text-center mb-55\">\n");
      out.write("                        <h2>단어 학습하기</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"courses-actives\">\n");
      out.write("\n");
      out.write("                <div class=\"properties pb-20\">\n");
      out.write("                    <div class=\"properties__card\">\n");
      out.write("                        <div class=\"properties__img overlay1\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gallery/featured1.png\"\n");
      out.write("                                 alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"properties__caption\">\n");
      out.write("                            <h3>오늘의 단어\n");
      out.write("                            </h3>\n");
      out.write("                            <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("                            </div>\n");
      out.write("                            <a href=\"toDayQuiz.do\"\n");
      out.write("                               class=\"border-btn border-btn2 cursor_pointer\">학습하기</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                ");

                    int i = 0;
                    for (Map<String, String> rMap : rQuizList) {
                        if (rMap.get("quiz_sort").equals("0")) {
                            i++;
                
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Single  start -->\n");
      out.write("                ");
      out.write("\n");
      out.write("<div class=\"properties pb-20\">\n");
      out.write("    <div class=\"properties__card\">\n");
      out.write("        <div class=\"properties__img overlay1\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gallery/featured");
      out.print((i%6)+1);
      out.write(".png\"\n");
      out.write("                 alt=\"\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"properties__caption\">\n");
      out.write("            <h3>");
      out.print(rMap.get("quiz_title") );
      out.write("\n");
      out.write("            </h3>\n");
      out.write("            <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("            </div>\n");
      out.write("            <a href=\"listPage.do?quizTitle=");
      out.print(rMap.get("quiz_title") );
      out.write("&quizSort=");
      out.print(rMap.get("quiz_sort") );
      out.write("\"\n");
      out.write("               class=\"border-btn border-btn2 cursor_pointer\">학습하기</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                <!-- Single end -->\n");
      out.write("\n");
      out.write("                ");

                        }
                    }
                
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Courses area End -->\n");
      out.write("    <!-- 단어 학습하기 end-->\n");
      out.write("\n");
      out.write("    <!-- 문장 학습하기 start-->\n");
      out.write("    <!-- Courses area start -->\n");
      out.write("    <div class=\"courses-area section-padding40 fix\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <div class=\"col-xl-7 col-lg-8\">\n");
      out.write("                    <div class=\"section-tittle text-center mb-55\">\n");
      out.write("                        <h2>문장 학습하기</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"courses-actives\">\n");
      out.write("\n");
      out.write("                ");

                    i = 0;
                    for (Map<String, String> rMap : rQuizList) {
                        if (rMap.get("quiz_sort").equals("1")) {
                            i++;
                
      out.write("\n");
      out.write("\n");
      out.write("                <!-- Single  start -->\n");
      out.write("                ");
      out.write("\n");
      out.write("<div class=\"properties pb-20\">\n");
      out.write("    <div class=\"properties__card\">\n");
      out.write("        <div class=\"properties__img overlay1\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gallery/featured");
      out.print((i%6)+1);
      out.write(".png\"\n");
      out.write("                 alt=\"\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"properties__caption\">\n");
      out.write("            <h3>");
      out.print(rMap.get("quiz_title") );
      out.write("\n");
      out.write("            </h3>\n");
      out.write("            <div class=\"properties__footer d-flex justify-content-between align-items-center\">\n");
      out.write("            </div>\n");
      out.write("            <a href=\"listPage.do?quizTitle=");
      out.print(rMap.get("quiz_title") );
      out.write("&quizSort=");
      out.print(rMap.get("quiz_sort") );
      out.write("\"\n");
      out.write("               class=\"border-btn border-btn2 cursor_pointer\">학습하기</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                <!-- Single end -->\n");
      out.write("\n");
      out.write("                ");

                        }
                    }
                
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Courses area End -->\n");
      out.write("    <!-- 문장 학습하기 end -->\n");
      out.write("\n");
      out.write("    ");
 if (SS_USER_TYPE.equals("ADMIN")) { 
      out.write("\n");
      out.write("    <div class=\"row justify-content-center\">\n");
      out.write("        <button class=\"boxed-btn\" style=\"font-weight: bold;margin-top: 10px;\"\n");
      out.write("                onclick=\"location.href='create.do'\">생성하기\n");
      out.write("        </button>\n");
      out.write("        <button class=\"boxed-btn admin_deleteBtn\" style=\"font-weight: bold;margin-top: 10px;margin-left: 10px;\"\n");
      out.write("                onclick=\"location.href='adminQuizList.do'\">삭제하기\n");
      out.write("        </button>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("    <!--? top subjects Area Start -->\n");
      out.write("    <div class=\"topic-area section-padding40\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <div class=\"col-xl-7 col-lg-8\">\n");
      out.write("                    <div class=\"section-tittle text-center mb-55\">\n");
      out.write("                        <h2>나의 문제 리스트</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("                ");

                    int userQuizTitleIdx = 0;
                    for (String userQuizTitle : rUserQuizTitleList) {
                        userQuizTitleIdx++;
                        if (userQuizTitleIdx == 9) {
                            break;
                        }
                
      out.write("\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 cursor_pointer\"\n");
      out.write("                     onclick=\"location.href='listPage.do?quizTitle=");
      out.print(userQuizTitle);
      out.write("&quizSort=2'\">\n");
      out.write("                    <div class=\"single-topic text-center mb-30\">\n");
      out.write("                        <div class=\"topic-img\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/gallery/topic");
      out.print((userQuizTitleIdx%8)+1);
      out.write(".png\"\n");
      out.write("                                 alt=\"\">\n");
      out.write("                            <div class=\"topic-content-box\">\n");
      out.write("                                <div class=\"topic-content\">\n");
      out.write("                                    <h3 class=\"topic-content-style\">");
      out.print(userQuizTitle);
      out.write("\n");
      out.write("                                    </h3>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                ");
 }
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <button class=\"boxed-btn\" style=\"font-weight: bold;margin-top: 10px;\"\n");
      out.write("                        onclick=\"location.href='userQuizList.do'\">전체보기\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- top subjects End -->\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!--다이어리작성하기-->\n");
      out.write("    <!--? top subjects Area Start -->\n");
      out.write("    <div class=\"topic-area section-padding40\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <div class=\"col-xl-7 col-lg-8\">\n");
      out.write("                    <div class=\"section-tittle text-center mb-55\">\n");
      out.write("                        <h2>나의 일기쓰기</h2>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <button class=\"boxed-btn\" style=\"font-weight: bold;margin-top: 10px;\"\n");
      out.write("                        onclick=\"location.href='quizeWrite.do'\">일기 작성하기\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- ? services-area -->\n");
      out.write("    <div class=\"services-area services-area2 section-padding40\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-sm-center\">\n");
      out.write("                <div class=\"chatBox col-lg-4 col-md-6 col-sm-8\">\n");
      out.write("                    <div class=\"single-services mb-30 cursor_pointer apiButton\" onclick=\"location.href='apiChat.do'\">\n");
      out.write("                        <div class=\"features-icon\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/icon/icon2.svg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"features-caption\">\n");
      out.write("                            <h3>심심이</h3>\n");
      out.write("                            <p>심심이와 대화를 해보세요!</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"chatBox col-lg-4 col-md-6 col-sm-8\">\n");
      out.write("                    <div class=\"single-services mb-30 cursor_pointer apiButton\" onclick=\"location.href='userChat.do'\">\n");
      out.write("                        <div class=\"features-icon\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/icon/icon1.svg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"features-caption\">\n");
      out.write("                            <h3>단체 채팅하기</h3>\n");
      out.write("                            <p>당신의 실력을 보여주세요!</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"chatBox col-lg-4 col-md-6 col-sm-8\">\n");
      out.write("                    <div class=\"single-services mb-30 cursor_pointer apiButton\" onclick=\"location.href='/wordGame.do'\">\n");
      out.write("                        <div class=\"features-icon\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/icon/icon1.svg\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"features-caption\">\n");
      out.write("                            <h3>단어 끝말잇기</h3>\n");
      out.write("                            <p>재밌는 게임 해요~</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<!-- footer&Scroll Up start -->\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-wrappper footer-bg\">\n");
      out.write("        <!-- footer-bottom area -->\n");
      out.write("        <div class=\"footer-bottom-area\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"footer-border\">\n");
      out.write("                    <div class=\"row d-flex align-items-center\">\n");
      out.write("                        <div class=\"col-xl-12 \">\n");
      out.write("                            <div class=\"footer-copy-right text-center\">\n");
      out.write("                                <p>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>\n");
      out.write("                                    All rights reserved | This template is made with <i class=\"fa fa-heart\"\n");
      out.write("                                                                                        aria-hidden=\"true\"></i> by <a\n");
      out.write("                                        href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Scroll Up -->\n");
      out.write("<div id=\"back-top\">\n");
      out.write("    <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("</div>");
      out.write("\n");
      out.write("<!-- footer&Scroll Up end -->\n");
      out.write("\n");
      out.write("<!-- js file start -->\n");
      out.write("\n");
      out.write("<!-- JS here -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modernizr-3.5.0.min.js\"></script>\n");
      out.write("<!-- Jquery, Popper, Bootstrap -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\n");
      out.write("<!-- Jquery Mobile Menu -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.slicknav.min.js\"></script>\n");
      out.write("<!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/slick.min.js\"></script>\n");
      out.write("<!-- Progress -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.barfiller.js\"></script>\n");
      out.write("<!-- counter , waypoint,Hover Direction -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/hover-direction-snake.min.js\"></script>\n");
      out.write("<!-- Jquery Plugins, main Jquery -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("<!-- js file end -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
