/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-12-14 11:19:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.chat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;

public final class apiChat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/view/inc/preloader.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/jsfile.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/header.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/footer.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/head.jsp", Long.valueOf(1634277451000L));
    _jspx_dependants.put("/WEB-INF/view/inc/section.jsp", Long.valueOf(1634277451000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!-- head Start -->\n");
      out.write("    ");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\n");
      out.write("<title>S&S</title>\n");
      out.write("<meta name=\"description\" content=\"See&Speech\">\n");
      out.write("<meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/hero/hero2.png\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.ico\">\n");
      out.write("\n");
      out.write("<!-- CSS here -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slicknav.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themify-icons.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/slick.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/animate.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/fontawesome-free-5.15.3-web/css/all.min.css\">");
      out.write("\n");
      out.write("    <!-- head end -->\n");
      out.write("\n");
      out.write("    <!-- chat CSS -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/chatcore.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/chatstyle.css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/page/apiChat.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- Preloader Start -->\n");
      out.write("\n");
      out.write("<div id=\"preloader-active\">\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"preloader-inner position-relative\">\n");
      out.write("            <div class=\"preloader-circle\"></div>\n");
      out.write("            <div class=\"preloader-img pere-text\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snsloder.png\" alt=\"\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("<!-- Preloader end -->\n");
      out.write("\n");
      out.write("<!-- header start -->\n");
      out.write('\n');
      out.write('\n');

    String SS_USER_EMAIL = CmmUtil.nvl((String) session.getAttribute("SS_USER_EMAIL"));

      out.write("\n");
      out.write("<header>\n");
      out.write("    <div class=\"header-area header-transparent\">\n");
      out.write("        <div class=\"main-header \">\n");
      out.write("            <div class=\"header-bottom  header-sticky\">\n");
      out.write("                <div class=\"container-fluid\">\n");
      out.write("                    <div class=\"row align-items-center\">\n");
      out.write("                        <!-- Logo -->\n");
      out.write("                        <div class=\"col-xl-2 col-lg-2\">\n");
      out.write("                            <div class=\"logo\">\n");
      out.write("                                <a href=\"index.do\"><img\n");
      out.write("                                        src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo/snslogo.png\" alt=\"\"></a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-xl-10 col-lg-10\">\n");
      out.write("                            <div class=\"menu-wrapper d-flex align-items-center justify-content-end\">\n");
      out.write("                                <!-- Main-menu -->\n");
      out.write("                                <div class=\"main-menu d-none d-lg-block\">\n");
      out.write("                                    <nav>\n");
      out.write("                                        <ul id=\"navigation\">\n");
      out.write("                                            <li class=\"active\"><a href=\"index.do\">Home</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"userPage.do\">User</a></li>\n");
      out.write("                                            <li class=\"active\"><a href=\"rank.do\">Rank</a></li>\n");
      out.write("                                            <!-- Button -->\n");
      out.write("                                            ");
 if (SS_USER_EMAIL.equals("")) { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"loginPage.do\" class=\"btn btn3\">Log in</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } else { 
      out.write("\n");
      out.write("                                            <li class=\"button-header\"><a href=\"logout.do\" class=\"btn btn3\">Log out</a>\n");
      out.write("                                            </li>\n");
      out.write("                                            ");
 } 
      out.write("\n");
      out.write("                                        </ul>\n");
      out.write("                                    </nav>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- Mobile Menu -->\n");
      out.write("                        <div class=\"col-12\">\n");
      out.write("                            <div class=\"mobile_menu d-block d-lg-none\"></div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>");
      out.write("\n");
      out.write("<!-- header end -->\n");
      out.write("\n");
      out.write("<main style=\"overflow-x:hidden\">\n");
      out.write("    <!-- slider Area Start-->\n");
      out.write("    ");
      out.write("\n");
      out.write("<section class=\"slider-area slider-area2\">\n");
      out.write("    <div class=\"slider-active\">\n");
      out.write("        <!-- Single Slider -->\n");
      out.write("        <div class=\"single-slider slider-height2\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-xl-8 col-lg-11 col-md-12\">\n");
      out.write("                        <div class=\"hero__caption hero__caption2\">\n");
      out.write("                            <h1 data-animation=\"bounceIn\" data-delay=\"0.2s\">See & Speech</h1>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>");
      out.write("\n");
      out.write("    <!-- slider Area end-->\n");
      out.write("\n");
      out.write("    <div class=\"main-container\" style=\"padding-top: 0;\">\n");
      out.write("        <div class=\"pd-ltr-20 xs-pd-20-10\">\n");
      out.write("            <div class=\"min-height-200px\">\n");
      out.write("                <div class=\"bg-white border-radius-4 box-shadow mb-30\">\n");
      out.write("                    <div class=\"row no-gutters\">\n");
      out.write("                        <div class=\"col-lg-9 col-md-8 col-sm-12\">\n");
      out.write("                            <div class=\"chat-detail\">\n");
      out.write("                                <div class=\"chat-profile-header clearfix\">\n");
      out.write("                                    <div class=\"left\">\n");
      out.write("                                        <div class=\"clearfix\">\n");
      out.write("                                            <div class=\"chat-profile-name chat_head_box\">\n");
      out.write("                                                <i class=\"fas fa-angle-left fa-2x\" style=\"cursor: pointer;\"\n");
      out.write("                                                   onclick=\"history.back()\"></i>\n");
      out.write("                                                <h3>심심이</h3>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"chat-box\">\n");
      out.write("                                    <div class=\"chat-desc customscroll\">\n");
      out.write("                                        <ul id=\"chat__ul\">\n");
      out.write("\n");
      out.write("                                            <li class=\"clearfix\">\n");
      out.write("                                                        <span class=\"chat-img\">\n");
      out.write("                                                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/chat/sim.png\"\n");
      out.write("                                                                 alt=\"\">\n");
      out.write("                                                        </span>\n");
      out.write("                                                <div class=\"chat-body clearfix\">\n");
      out.write("                                                    <p>하이!</p>\n");
      out.write("                                                    <div class=\"chat_time init_chat_time\"></div>\n");
      out.write("                                                </div>\n");
      out.write("                                            </li>\n");
      out.write("\n");
      out.write("                                        </ul>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"chat-footer\">\n");
      out.write("                                        <div id=\"micButtonBox\"></div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<!-- footer&Scroll Up start -->\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-wrappper footer-bg\">\n");
      out.write("        <!-- footer-bottom area -->\n");
      out.write("        <div class=\"footer-bottom-area\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"footer-border\">\n");
      out.write("                    <div class=\"row d-flex align-items-center\">\n");
      out.write("                        <div class=\"col-xl-12 \">\n");
      out.write("                            <div class=\"footer-copy-right text-center\">\n");
      out.write("                                <p>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>\n");
      out.write("                                    All rights reserved | This template is made with <i class=\"fa fa-heart\"\n");
      out.write("                                                                                        aria-hidden=\"true\"></i> by <a\n");
      out.write("                                        href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("                                </p>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<!-- Scroll Up -->\n");
      out.write("<div id=\"back-top\">\n");
      out.write("    <a title=\"Go to Top\" href=\"#\"> <i class=\"fas fa-level-up-alt\"></i></a>\n");
      out.write("</div>");
      out.write("\n");
      out.write("<!-- footer&Scroll Up end -->\n");
      out.write("\n");
      out.write("<!-- js file start -->\n");
      out.write("\n");
      out.write("<!-- JS here -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/modernizr-3.5.0.min.js\"></script>\n");
      out.write("<!-- Jquery, Popper, Bootstrap -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.6.0.min.js\"></script>\n");
      out.write("<!-- Jquery Mobile Menu -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.slicknav.min.js\"></script>\n");
      out.write("<!-- Jquery Slick , Owl-Carousel Plugins -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/slick.min.js\"></script>\n");
      out.write("<!-- Progress -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.barfiller.js\"></script>\n");
      out.write("<!-- counter , waypoint,Hover Direction -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/hover-direction-snake.min.js\"></script>\n");
      out.write("<!-- Jquery Plugins, main Jquery -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>");
      out.write("\n");
      out.write("<!-- js file end -->\n");
      out.write("\n");
      out.write("<!-- chat js -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chatcore.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chatscript.min.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/chatlayout-settings.js\"></script>\n");
      out.write("\n");
      out.write("<!-- annyang js & speechkitt -->\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/annyang.js\"></script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/speechkitt.js\"></script>\n");
      out.write("<script>\n");
      out.write("    function getDatetime() {\n");
      out.write("        let _date = new Date();\n");
      out.write("        let _hours = _date.getHours();\n");
      out.write("        let _min = _date.getMinutes();\n");
      out.write("        _hours = _hours < 10 ? '0' + _hours : _hours\n");
      out.write("        _min = _min < 10 ? '0' + _min : _min\n");
      out.write("        return _hours + ':' + _min;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // 첫번째 심심이 말풍선 시간 init\n");
      out.write("    let dateInitTime = getDatetime();\n");
      out.write("    document.querySelector(\".init_chat_time\").innerHTML = dateInitTime;\n");
      out.write("\n");
      out.write("    /* ##### 음성 인식 Annyang.js start ##### */\n");
      out.write("    if (annyang) {\n");
      out.write("        // Add our commands to annyang\n");
      out.write("        annyang.addCommands({});\n");
      out.write("\n");
      out.write("        //음성인식 값 받아오기위한 객체 생성\n");
      out.write("        let recognition = annyang.getSpeechRecognizer();\n");
      out.write("        //최종 음성인식 결과값 저장 변수\n");
      out.write("        let final_transcript = \"\";\n");
      out.write("        //말하는 동안에 인식되는 값 가져오기(허용)\n");
      out.write("        recognition.interimResults = false;\n");
      out.write("        //음성 인식결과 가져오기\n");
      out.write("        recognition.onresult = function (event) {\n");
      out.write("            final_transcript = \"\";\n");
      out.write("            for (let i = event.resultIndex; i < event.results.length; ++i) {\n");
      out.write("                if (event.results[i].isFinal) {\n");
      out.write("                    final_transcript += event.results[i][0].transcript;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            console.log(\"final :\" + final_transcript);\n");
      out.write("\n");
      out.write("            // 사용자 음성 html append\n");
      out.write("            let dateTime = getDatetime();\n");
      out.write("            let resHTML = \"\";\n");
      out.write("            resHTML += '<li class=\"clearfix admin_chat\">';\n");
      out.write("            resHTML += '<span class=\"chat-img\">';\n");
      out.write("            resHTML += '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/chat/chat-img.jpg\">';\n");
      out.write("            resHTML += '</span>';\n");
      out.write("            resHTML += '<div class=\"chat-body clearfix\">';\n");
      out.write("            resHTML += '<p>' + final_transcript + '</p>';\n");
      out.write("            resHTML += '<div class=\"chat_time\">' + dateTime + '</div>';\n");
      out.write("            resHTML += '</div>';\n");
      out.write("            resHTML += '</li>';\n");
      out.write("            $(\"#chat__ul\").append(resHTML);\n");
      out.write("\n");
      out.write("            // 심심이 api ajax\n");
      out.write("            $.ajax({\n");
      out.write("                url: \"/chat/msg.do\",\n");
      out.write("                type: \"post\",\n");
      out.write("                dataType: \"JSON\",\n");
      out.write("                data: {\"send_msg\": final_transcript},\n");
      out.write("                success: function (json) {\n");
      out.write("                    let _dateTime = getDatetime();\n");
      out.write("\n");
      out.write("                    // console.log(json.res_msg);\n");
      out.write("                    resHTML = \"\";\n");
      out.write("                    resHTML += '<li class=\"clearfix\">';\n");
      out.write("                    resHTML += '<span class=\"chat-img\">';\n");
      out.write("                    resHTML += '<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/chat/sim.png\">';\n");
      out.write("                    resHTML += '</span>';\n");
      out.write("                    resHTML += '<div class=\"chat-body clearfix\">';\n");
      out.write("                    resHTML += '<p>' + json.res_msg + '</p>';\n");
      out.write("                    resHTML += '<div class=\"chat_time\">' + _dateTime + '</div>';\n");
      out.write("                    resHTML += '</div>';\n");
      out.write("                    resHTML += '</li>';\n");
      out.write("                    $(\"#chat__ul\").append(resHTML);\n");
      out.write("                }\n");
      out.write("            })\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        // Tell KITT to use annyang\n");
      out.write("        SpeechKITT.annyang();\n");
      out.write("\n");
      out.write("        // Define a stylesheet for KITT to use\n");
      out.write("        SpeechKITT.setStylesheet('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/themes/flat.css');\n");
      out.write("\n");
      out.write("        // Render KITT's interface\n");
      out.write("        SpeechKITT.vroom();\n");
      out.write("    }\n");
      out.write("    /* ##### 음성 인식 Annyang.js end ##### */\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
